/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyKissesRouteImport } from './routes/my-kisses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIdRouteImport } from './routes/upload.$id'
import { Route as KissIdRouteImport } from './routes/kiss.$id'

const MyKissesRoute = MyKissesRouteImport.update({
  id: '/my-kisses',
  path: '/my-kisses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIdRoute = UploadIdRouteImport.update({
  id: '/upload/$id',
  path: '/upload/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KissIdRoute = KissIdRouteImport.update({
  id: '/kiss/$id',
  path: '/kiss/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-kisses': typeof MyKissesRoute
  '/kiss/$id': typeof KissIdRoute
  '/upload/$id': typeof UploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-kisses': typeof MyKissesRoute
  '/kiss/$id': typeof KissIdRoute
  '/upload/$id': typeof UploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-kisses': typeof MyKissesRoute
  '/kiss/$id': typeof KissIdRoute
  '/upload/$id': typeof UploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/my-kisses' | '/kiss/$id' | '/upload/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/my-kisses' | '/kiss/$id' | '/upload/$id'
  id: '__root__' | '/' | '/login' | '/my-kisses' | '/kiss/$id' | '/upload/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyKissesRoute: typeof MyKissesRoute
  KissIdRoute: typeof KissIdRoute
  UploadIdRoute: typeof UploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-kisses': {
      id: '/my-kisses'
      path: '/my-kisses'
      fullPath: '/my-kisses'
      preLoaderRoute: typeof MyKissesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$id': {
      id: '/upload/$id'
      path: '/upload/$id'
      fullPath: '/upload/$id'
      preLoaderRoute: typeof UploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiss/$id': {
      id: '/kiss/$id'
      path: '/kiss/$id'
      fullPath: '/kiss/$id'
      preLoaderRoute: typeof KissIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyKissesRoute: MyKissesRoute,
  KissIdRoute: KissIdRoute,
  UploadIdRoute: UploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
